import "./globals.css";
import CustomLayout from "@/components/layouts/CustomLayout";
import Providers from "@/redux/Providers";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("accessToken");
  return (
    <html lang="en">
      <body className="font-Montserrat">
        <Providers>
          <CustomLayout token={token?.value}>{children}</CustomLayout>
        </Providers>
        <div id="modal" />
      </body>
    </html>
  );
}
