import HomePage from "@/components/HomePage";
import Image from "next/image";
export const metadata = {
  title: "Home - Coders Choice",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <HomePage />
    </div>
  );
}
